CoreArsaOfisi/Controllers/SecurityController.cs
using CoreArsaOfisi.DataLayer.Models.db;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace CoreArsaOfisi.Controllers
{
    public class SecurityController : Controller
    {
        private readonly ILogger<SecurityController> _logger;
        private readonly u9673886_arsdbContext _db;

        public SecurityController(ILogger<SecurityController> logger, u9673886_arsdbContext db)
        {
            _logger = logger;
            _db = db;
        }

        [Route("giris")]
        [HttpGet]
        public IActionResult Login()
        {
            u9673886_arsdbContext db = new u9673886_arsdbContext();
            var vIlanlar = db.Advertisements.ToList();
            return View();
        }

        [Route("giris")]
        [HttpPost]
        public async Task<IActionResult> Login(Advertiser _advertiser)
        {
            var vHangiKullanici = _db.Advertisers.FirstOrDefault(w => w.Mail == _advertiser.Mail && w.Password == _advertiser.Password);
            if (vHangiKullanici != null)
            {
                var claims = new List<Claim>
                {
                    new Claim("kullanici_id",vHangiKullanici.Id.ToString()),
                    new Claim("kullanici_adi",vHangiKullanici.OfficalName),
                    new Claim("kullanici_mail",vHangiKullanici.Mail),
                    new Claim("kullanici_avatar",vHangiKullanici.Avatar),
                };
                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                var principal = new ClaimsPrincipal(claimsIdentity);
                var authProperties = new AuthenticationProperties
                {
                    //AllowRefresh = <bool>,
                    // Refreshing the authentication session should be allowed.

                    ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(1440),
                    // The time at which the authentication ticket expires. A 
                    // value set here overrides the ExpireTimeSpan option of 
                    // CookieAuthenticationOptions set with AddCookie.

                    IsPersistent = true,
                    // Whether the authentication session is persisted across 
                    // multiple requests. When used with cookies, controls
                    // whether the cookie's lifetime is absolute (matching the
                    // lifetime of the authentication ticket) or session-based.

                    //IssuedUtc = <DateTimeOffset>,
                    // The time at which the authentication ticket was issued.

                    //RedirectUri = <string>
                    // The full path or absolute URI to be used as an http 
                    // redirect response value.
                };
                await HttpContext.SignInAsync(principal, authProperties);

                //var vGirisYapanKullanici = claimsIdentity.FindFirst("kullanici_mail").Value.ToString(); Claim Okuma İşlemi
                return RedirectToAction("Index", "Home");
            }
            else
            {
                TempData["rejection"] = "Kullanıcı Adı veya Parolanız Yanlış.";
                return View();//Giriş Başarısız ise Yönlendir.
            }
        }

        [Route("cikis")]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(
            CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Login");
        }
    }
}

CoreArsaOfisi/Controllers/UserController.cs
using CoreArsaOfisi.DataLayer.Models.db;
using CoreArsaOfisi.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace CoreArsaOfisi.Controllers
{
    public class UserController : AppController
    {
        private readonly u9673886_arsdbContext _db;
        private readonly IWebHostEnvironment _hostingEnvironment;

        

        public UserController(u9673886_arsdbContext db, IWebHostEnvironment hostingEnvironment)
        {
            _db = db;
            _hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Dashboard()
        {
            return View();
        }

        [Route("ilanlarim")]
        [HttpGet]
        public async Task<IActionResult> MyAds()
        {
            var model = await _db.VIlanListesis.Where(w => w.AdvertiserId == Convert.ToInt32(CurrentUser.KullaniciId)).ToListAsync();
            return View(model);
        }


        [Route("profilim")]
        [HttpGet]
        public async Task<IActionResult> MyProfile()
        {
            var model = await _db.Advertisers.Include("SocialMedium").Where(w => w.Id == Convert.ToInt32(CurrentUser.KullaniciId)).FirstOrDefaultAsync();
            return View(model);
        }

        [Route("profilim")]
        [HttpPost]
        public async Task<IActionResult> MyProfile(Advertiser _advertiser, bool? ProfilTetikleyici, bool? SosyalMedyaTetikleyici, bool? ParolaTetikleyici, List<IFormFile> avatar)
        {
            var vHangiKullanici = await _db.Advertisers.Include("SocialMedium").Where(w => w.Id == Convert.ToInt32(CurrentUser.KullaniciId)).FirstOrDefaultAsync();
            if (ProfilTetikleyici != null && ProfilTetikleyici != false)
            {
                if (avatar != null)
                {
                    var vSilinecekDosya = Path.Combine(_hostingEnvironment.WebRootPath, "userimage", vHangiKullanici.Avatar.ToString());
                    var vDosyaBilgisi = new System.IO.FileInfo(vSilinecekDosya.ToString());

                    if (vDosyaBilgisi.Exists)
                    {
                        vDosyaBilgisi.Delete();
                    }

                    foreach (var item in avatar)
                    {
                        var InputFileName = Path.GetFileName(item.FileName);
                        string sBenzersizIsim = Guid.NewGuid().ToString("N") + Path.GetExtension(item.FileName);
                        string stream = Path.Combine(_hostingEnvironment.WebRootPath, "userimage", sBenzersizIsim);
                        FileStream ky = new FileStream(stream, FileMode.Create);
                        await item.CopyToAsync(ky);
                        ky.Close();
                        vHangiKullanici.Avatar = sBenzersizIsim;
                    }
                }
                vHangiKullanici.CompanyName = _advertiser.CompanyName;
                vHangiKullanici.OfficalName = _advertiser.OfficalName;
                vHangiKullanici.PhoneNumber = _advertiser.PhoneNumber;
                vHangiKullanici.LandPhone = _advertiser.LandPhone;
                vHangiKullanici.WhatsappNumber = _advertiser.WhatsappNumber;
                vHangiKullanici.Mail = _advertiser.Mail;
                await _db.SaveChangesAsync();
            }
            else if (SosyalMedyaTetikleyici != null && SosyalMedyaTetikleyici != false)
            {
                vHangiKullanici.SocialMedium.Skype = _advertiser.SocialMedium.Skype;
                vHangiKullanici.SocialMedium.WebSite = _advertiser.SocialMedium.WebSite;
                vHangiKullanici.SocialMedium.Facebook = _advertiser.SocialMedium.Facebook;
                vHangiKullanici.SocialMedium.Twitter = _advertiser.SocialMedium.Twitter;
                vHangiKullanici.SocialMedium.Linkedin = _advertiser.SocialMedium.Linkedin;
                vHangiKullanici.SocialMedium.Instagram = _advertiser.SocialMedium.Instagram;
                vHangiKullanici.SocialMedium.GooglePlus = _advertiser.SocialMedium.GooglePlus;
                vHangiKullanici.SocialMedium.Youtube = _advertiser.SocialMedium.Youtube;
                vHangiKullanici.SocialMedium.Pinterest = _advertiser.SocialMedium.Pinterest;
                vHangiKullanici.SocialMedium.Vimeo = _advertiser.SocialMedium.Vimeo;
                await _db.SaveChangesAsync();
            }
            else if (ParolaTetikleyici != null && ParolaTetikleyici != false)
            {
                vHangiKullanici.Password = _advertiser.Password;
                await _db.SaveChangesAsync();
            }
            return RedirectToAction("MyProfile");
        }
    }
}

CoreArsaOfisi/Views/Shared/Components/HeaderAdmin/Default.cshtml
@using Microsoft.AspNetCore.Authentication.Cookies
@{
    var claimsIdentity = User.Identity as System.Security.Claims.ClaimsIdentity;
}
<!-- Main Header Nav -->
<header class="header-nav menu_style_home_one style2 menu-fixed main-menu">
    <div class="container-fluid p0">
        <!-- Ace Responsive Menu -->
        <nav>
            <!-- Menu Toggle btn-->
            <div class="menu-toggle">
                <img class="nav_logo_img img-fluid" src="~/images/header-logo2.png" alt="header-logo.png">
                <button type="button" id="menu-btn">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <a href="@Url.Action("Index","Home")" class="navbar_brand float-left dn-smd">
                <img class="logo1 img-fluid" src="~/images/header-logo2.png" alt="header-logo.png">
                <img class="logo2 img-fluid" src="~/images/header-logo2.png" alt="header-logo2.png">
                <span>Arsaofisi</span>
            </a>
            <!-- Responsive Menu Structure-->
            <!--Note: declare the Menu style in the data-menu-style="horizontal" (options: horizontal, vertical, accordion) -->
            <ul id="respMenu" class="ace-responsive-menu text-right" data-menu-style="horizontal">
                <li class="last">
                    <a href="@Url.Action("Index","Home")"><span class="title">Anasayfa</span></a>
                </li>
                <li class="last">
                    <a href="@Url.Action("List","Home")"><span class="title">İlanlar</span></a>
                </li>
                <li class="last">
                    <a href="@Url.Action("About","Home")"><span class="title">Hakkımızda</span></a>
                </li>
                <li class="last">
                    <a href="@Url.Action("Contact","Home")"><span class="title">İletişim</span></a>
                </li>
                <li class="user_setting">
                    <div class="dropdown">
                        <a class="btn dropdown-toggle" href="#" data-toggle="dropdown">
                            <img style="width:45px;height:45px" class="rounded-circle" src="~/userimage/@claimsIdentity.FindFirst("kullanici_avatar").Value.ToString()" alt="Kullanici Gorseli">
                            <span class="dn-1199">@claimsIdentity.FindFirst("kullanici_adi").Value.ToString()</span>
                        </a>
                        <div class="dropdown-menu">
                            <div class="user_set_header">
                                <img class="float-left" src="~/userimage/@claimsIdentity.FindFirst("kullanici_avatar").Value.ToString()" alt="Kullanici Gorseli" style="width:45px;height:45px;border-radius:25px 25px">
                                <p>
                                    @claimsIdentity.FindFirst("kullanici_adi").Value.ToString() <br><span class="address">
                                        <a href="https://grandetest.com/cdn-cgi/l/email-protection" class="__cf_email__">@claimsIdentity.FindFirst("kullanici_mail").Value.ToString()</a>
                                    </span>
                                </p>
                            </div>
                            <div class="user_setting_content">
                                <a class="dropdown-item active" href="@Url.Action("MyProfile","User")">Profilim</a>
                                <a class="dropdown-item" href="@Url.Action("LogOut","Security")">Çıkış Yap</a>
                            </div>
                        </div>
                    </div>
                </li>
                <li class="list-inline-item add_listing"><a href="@Url.Action("AdvertisementAdd","Advertisement")"><span class="flaticon-plus"></span><span class="dn-lg"> İLAN VER </span></a></li>
            </ul>
        </nav>
    </div>
</header>
<!-- Main Header Nav For Mobile -->
<div id="page" class="stylehome1 h0">
    <div class="mobile-menu">
        <div class="header stylehome1">
            <div class="main_logo_home2 text-center">
                <img class="nav_logo_img img-fluid mt20" src="~/images/header-logo2.png" alt="header-logo2.png">
                <span class="mt20">Çatalça Arsa Ofisi</span>
            </div>
            <ul class="menu_bar_home2">
                <li class="list-inline-item list_s"><a href="page-register.html"><span class="flaticon-user"></span></a></li>
                <li class="list-inline-item"><a href="#menu"><span></span></a></li>
            </ul>
        </div>
    </div><!-- /.mobile-menu -->
    <nav id="menu" class="stylehome1">
        <ul>
            <li><a href="page-contact.html">Contact</a></li>
            <li><a href="page-login.html"><span class="flaticon-user"></span> Login</a></li>
            <li><a href="page-register.html"><span class="flaticon-edit"></span> Register</a></li>
            <li class="cl_btn"><a class="btn btn-block btn-lg btn-thm circle" href="#"><span class="flaticon-plus"></span> Create Listing</a></li>
        </ul>
    </nav>
</div>